version: "3"

services:
  web:
    container_name: exampleapp
    restart: always
    build: .
    ports:
      - "5000:3000"
    links:
      - mongo
    volumes:
      - ./:/usr/src/app

  mongo:
    container_name: mymongodatabase
    image: mongo:4.4.6
    ports:
      - "27017:27017"
    logging:
      driver: none
    
